name: stepper_page_view
description: A custom stepper that displays steps in a page view
version: 0.0.3
homepage: "https://github.com/Nolence/stepper_page_view"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  dotted_line: ^3.1.0
  either_dart: ^0.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
